#ifndef QTMANHATTANSTYLE_GLOBAL_HPP
#define QTMANHATTANSTYLE_GLOBAL_HPP

#include <qglobal.h>

#if defined(QTMANHATTANSTYLE_LIBRARY)
#  define QTMANHATTANSTYLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTMANHATTANSTYLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTMANHATTANSTYLE_GLOBAL_HPP
